on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

name: Push Preview to Cloudflare Pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        working-directory: ./website
      - name: Build
        run: npm run build
        working-directory: ./website
      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "website"
          packageManager: npm
          command: pages deploy ./build/client --project-name=event-tracker --commit-dirty=true
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Built preview on Cloudflare Pages: ${{ steps.deploy.outputs.deployment-url }} [Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
            })
